#cloud-config
autoinstall:
  version: 1
  #refresh-installer: # start with an up-to-date installer
  #update: yes
  source:
    id: ubuntu-desktop
  channel: stable # update from the ubuntu stable branch only
  interactive-sections: # Install groups listed here will wait for user input
    - network
    - identity

  locale: en_US.UTF-8
  keyboard:
    layout: us
  timezone: Europe/Amsterdam
  ssh:
    allow-pw: true
    install-server: true
  storage:
    grub:
      update_nvram: true
      remove_duplicate_entries: true
      probe_additional_os: false
      reorder_uefi: false
    swap:
      filename: swap.img
      maxsize: 8GB
    config:
      # Disks
      - id: disk0
        type: disk
        ptable: gpt
        wipe: superblock
        grub_device: false
        match:
          size: largest
    layout:
      name: lvm
      password: lukspass
  snaps:
    - signal-desktop
    - mattermost-desktop
    - nextcloud-desktop-client
  packages:
    - pandoc
    - texlive
    - texlive-xetex
    - inotify-tools
    - csvkit
    - ghostwriter
    - meld
    - git
    - ubuntu-restricted-extras
